### PR TITLE
make sure downloader image is present and called non short name

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Addresses: https://github.com/containers/ai-lab-recipes/issues/592
Please review @n1hility @rhatdan 
cc @cooktheryan @prarit

Change: model downloader is not present as well as short name resolution (not sure if this is a problem yet until it becomes available)

### CODE REVIEW

**Comment by rhatdan** [comment]
I am working on a similar fix for this.  Want to add `--pull never` to the podman run commands.

**Comment by rhatdan** [comment]
I was putting the common code into ../common/

**Comment by Gregory-Pereira** [comment]
Ive both tagged this as `local` instead of `latest` as well as add the pull never

**Comment by rhatdan** [comment]
I now like mine better, lets continue on that one.

**Pull request closed without merging**
