### PR TITLE
update chatapp readme

### PR DESCRIPTION
**Pull request by MichaelClifford**
Add more details to the chat app readme

### CODE REVIEW

**Comment by MichaelClifford** [comment]
cc @slemeur

**Comment by MichaelClifford** [comment]
Partially address #84

**Review by jeffmaury — APPROVED** [review]
LGTM. Relative URLs are not supported as this file will be embedded in the recipe catalog but don't know yet how it will be rendered

**Comment by MichaelClifford** [comment]
@jeffmaury should I replace all the relative links with github urls before merging?

**Pull request merged**
