### PR TITLE
Make output a subdir of build, to allow chown to work

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
Replaces: https://github.com/containers/ai-lab-recipes/pull/597

**Comment by rhatdan** [comment]
@javipolo PTAL

**Comment by rhatdan** [comment]
@achilleas-k PTAL

**Comment by rhatdan** [comment]
@Gregory-Pereira @sallyom PTAL

**Review by Gregory-Pereira — APPROVED** [review]
/lgtm

**Pull request merged**
