### PR TITLE
Improve Makefiles

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@cgwalters PTAL

**Comment by rhatdan** [comment]
@lmilbaum @sallyom @Gregory-Pereira @cooktheryan PTAL

**Review by Gregory-Pereira — APPROVED** [review]
/lgtm, let me know what of these training images we want to see worked into CI

**Comment by rhatdan** [comment]
The training objects take a long time to process and move a ton of data around.  So you could try with deepspeed and vllm to start.

**Pull request merged**
