### PR TITLE
intel-bootc image fixes

### PR DESCRIPTION
**Pull request by enriquebelarte**
Containerfile remade to use packages from habanalabs repo.

### CODE REVIEW

**Comment by enriquebelarte** [comment]
/hold

Need extra work to make it run from repo.

**Comment by lmilbaum** [comment]
rebase is needed

**Comment by rhatdan** [comment]
@enriquebelarte When you rebase, if https://github.com/containers/ai-lab-recipes/pull/489 is not merged, please add it to this PR so we will blow each other up.

**Comment by enriquebelarte** [comment]
It's rebased yet but I can add your changes here if you want to.

**Pull request closed without merging**
