### PR TITLE
fixes break that was introduced

### PR DESCRIPTION
**Pull request by cooktheryan**
Fixes breakage with the test here https://github.com/containers/ai-lab-recipes/actions/runs/9417989188

Initially thought we were in the clear after my initial PR merged

### CODE REVIEW

**Comment by cooktheryan** [comment]
local build results

```
e3c6246e
Successfully built llama-cpp-python
Installing collected packages: websockets, uvloop, ujson, typing-extensions, sniffio, shellingham, PyYAML, python-multipart, python-dotenv, pygments, orjson, numpy, mdurl, MarkupSafe, idna, httptools, h11, dnspython, diskcache, click, certifi, annotated-types, uvicorn, pydantic-core, markdown-it-py, jinja2, httpcore, email_validator, anyio, watchfiles, starlette, rich, pydantic, llama-cpp-python, httpx, typer, starlette-context, sse-starlette, pydantic-settings, fastapi-cli, fastapi
Successfully installed MarkupSafe-2.1.5 PyYAML-6.0.1 annotated-types-0.7.0 anyio-4.4.0 certifi-2024.6.2 click-8.1.7 diskcache-5.6.3 dnspython-2.6.1 email_validator-2.1.1 fastapi-0.111.0 fastapi-cli-0.0.4 h11-0.14.0 httpcore-1.0.5 httptools-0.6.1 httpx-0.27.0 idna-3.7 jinja2-3.1.4 llama-cpp-python-0.2.76 markdown-it-py-3.0.0 mdurl-0.1.2 numpy-1.26.4 orjson-3.10.3 pydantic-2.7.3 pydantic-core-2.18.4 pydantic-settings-2.3.1 pygments-2.18.0 python-dotenv-1.0.1 python-multipart-0.0.9 rich-13.7.1 shellingham-1.5.4 sniffio-1.3.1 sse-starlette-2.1.0 starlette-0.37.2 starlette-context-0.3.6 typer-0.12.3 typing-extensions-4.12.1 ujson-5.10.0 uvicorn-0.30.1 uvloop-0.19.0 watchfiles-0.22.0 websockets-12.0
STEP 11/11: ENTRYPOINT [ "sh", "run.sh" ]
COMMIT ghcr.io/containers/llamacpp-python-vulkan:latest
Getting image source signatures
Copying blob 9804fe384688 skipped: already exists
Copying blob e590a5edc3d7 skipped: already exists
Copying blob 3114cc9e3199 skipped: already exists
Copying blob cd147c2a3b94 skipped: already exists
Copying blob c3ce4592529b done   |
Copying config a7e892a00b done   |
Writing manifest to image destination
--> a7e892a00baf
Successfully tagged ghcr.io/containers/llamacpp-python-vulkan:latest
a7e892a00baf596b2928313fdc46b019a19407001ea867b430142da522a429e0
```

**Comment by Gregory-Pereira** [comment]
Ill fix the tests here when i get time.

**Comment by Gregory-Pereira** [comment]
Issue resulted from the fact that Vulkan and Cuda both work with GPUs but the tests were running for CPU only tests for vulkan which resulted in failure.

**Review by Gregory-Pereira — APPROVED** [review]
/lgtm

**Pull request merged**
