### PR TITLE
Add support for ARCH

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Review by Gregory-Pereira — APPROVED** [review]
/lgtm

**Comment by mrguitar** [comment]
It looks like more changes my be needed to make this work: 

```
STEP 11/14: RUN podman pull --root /usr/lib/containers/storage ${SERVERIMAGE}
Trying to pull quay.io/ai-lab/llamacpp-python:latest...
Getting image source signatures
Copying blob sha256:e45e0d55ad689a3c3aa7370812d229c535be128aed381a02b08e15e8f01af935
Copying blob sha256:7a2ac7b109a0ed4126f0b3b573255811b4fd300c7fb60e061a514a762d3d5d47
Copying blob sha256:e5d63390e36bd3fe7b8307e9ae99c34fbb82c28e17a33e3a04a584532816b041
Copying blob sha256:67a14e402c956d9726fb49bb81158d23b07c506cdd978279e9a6e2fafc899be0
Copying blob sha256:5d433aabd001724f7c8fae763b83a310635e7a5002d38d51961c254ab7708a3a
Error: copying system image from manifest list: writing blob: adding layer with blob "sha256:67a14e402c956d9726fb49bb81158d23b07c506cdd978279e9a6e2fafc899be0": processing tar file(Error: unrecognized command `podman /`

Did you mean this?
	cp
	ps
	rm

Try 'podman --help' for more information
): exit status 125
Error: building at STEP "RUN podman pull --root /usr/lib/containers/storage ${SERVERIMAGE}": while running runtime: exit status 125

make: *** [bootc] Error 125
```

**Comment by lmilbaum** [comment]
We should probably need to add tests for this use case in CI

**Comment by rhatdan** [comment]
That is cross compiling, the intent was not to fix that.  There is still an issue with the llama_python image causing the /opt issue.  Working on fixing this.

**Pull request merged**
