### PR TITLE
Simplify package installation

### PR DESCRIPTION
**Pull request by enriquebelarte**
Installs epel and CRB in a cleaner way.

### CODE REVIEW

**Review by lmilbaum — APPROVED** [review]
LGTM

**Comment by lmilbaum** [comment]
Is it an option to use variables instead of if/else commands?

**Comment by enriquebelarte** [comment]
> Is it an option to use variables instead of if/else commands?

Maybe for the `KERNEL_VERSION`, `TARGET_ARCH` and `OS_VERSION_MAJOR` we could leave out the conditionals (IINM there's no `else`) and add variables which could be cleaner and better for CI ? .  Regarding the packages based on different OSes I think it's OK as it is now, but I accept suggestions.

**Pull request merged**
