### PR TITLE
Fixing nvidia container file

### PR DESCRIPTION
**Pull request by tsorya**

### CODE REVIEW

**Comment by lmilbaum** [comment]
Would you mind checking why CI was not triggered on this PR and fix that on the way?

**Comment by tsorya** [comment]
> Would you mind checking why CI was not triggered on this PR and fix that on the way?

Looking

**Comment by tsorya** [comment]
opened https://github.com/containers/ai-lab-recipes/pull/674 to test ci issue, i think i found why it doesn't start but there is a problem with aws creds too

**Comment by lmilbaum** [comment]
> opened #674 to test ci issue, i think i found why it doesn't start but there is a problem with aws creds too

As discussed over Slack, lets differ the CI issue to a later stage. Please confirm the change has passed local tests and lets approve and merge this one. Please follow up with the push or/and scheduled workflows that they are still green.

**Comment by tsorya** [comment]
Tested locally, looks good

**Review by lmilbaum — APPROVED** [review]

**Pull request merged**
