### PR TITLE
add model service check

### PR DESCRIPTION
**Pull request by MichaelClifford**
This PR adds a check to the application to make sure the model service is running before proceeding. Once this PR is approved, we can roll out this same approach on the rest of the AI applications.

### CODE REVIEW

**Comment by jeffmaury** [comment]
Not sure this is related to this PR but the model service does not start:

image

**Comment by jeffmaury** [comment]
And seems the client application has opened its HTTP port:

image

image

**Comment by MichaelClifford** [comment]
> Not sure this is related to this PR but the model service does not start:
> 
> image

This PR does not make any changes to the model service. However, it looks like you may have added the environment variables incorrectly. This model service is the same as the playground, so it should be deployed the same way. 

`podman run -it -p 8001:8001 -v <LOCAL_PATH>locallm/models:/locallm/models:Z -e MODEL_PATH=models/mistral-7b-instruct-v0.1.Q4_K_M.gguf -e HOST=0.0.0.0 -e PORT=8001 llamacppserver`

**Comment by MichaelClifford** [comment]
> And seems the client application has opened its HTTP port:
> 
> image
> 
> image

yes, but it should not load the chat interface until the model service is ready. Do we need to have a stricter check in place?

**Comment by MichaelClifford** [comment]
Added an additional commit that incudes the same check in `chatbot/ai_applications/chat_ui.py`.

**Review by sallyom — APPROVED** [review]
LGTM

**Comment by jeffmaury** [comment]
@MichaelClifford can you rebase it so that it includes my latest patch

**Comment by MichaelClifford** [comment]
@jeffmaury rebased 😄

**Comment by jeffmaury** [comment]
LGTM, but the client application opens port 8501 before the model is loaded and if you use browser, you have this:

image

which is ok but I was wondering is there would be an option to replace `checking_model_service` by a more user friendly sentence

**Comment by jeffmaury** [comment]
Another suggestion: would also be good to have the time spent to get the model service available at the end of loop

**Comment by MichaelClifford** [comment]
@jeffmaury  How does this look?

Screenshot 2024-02-14 at 11 27 00 AM

**Review by lstocchi — APPROVED** [review]
Works fine for me

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by lstocchi** [comment]
merging as it has been approved by everyone. Thanks @MichaelClifford!!

**Pull request merged**
