### PR TITLE
add skopeo so that ilab model download will work

### PR DESCRIPTION
**Pull request by jeremyeder**
This is required for https://github.com/instructlab/instructlab/pull/1756 to work.

### CODE REVIEW

**Review by n1hility — APPROVED** [review]

**Comment by rhatdan** [comment]
@jeremyeder you need to sign your commit.

**Comment by rhatdan** [comment]
Also can  you put the same change in amd-bootc and intel-bootc.

In a perfect world ilab would be an RPM with a requirement on skopeo...

**Comment by n1hility** [comment]
Just an FYI that it’s inclusion at the bootc level is more for friendliness / diagnostic purposes. Ilab will be invoking a skopeo install inside the container with a host volume mount for output.

**Comment by romfreiman** [comment]
/hold
there is skopeo already:

[rom@rhelai ~]$ rpm -qf /usr/bin/skopeo
skopeo-1.14.3-3.el9_4.x86_64

**Pull request closed without merging**
