### PR TITLE
bug: Fix broken path in chatbot/bootc/Containerfile

### PR DESCRIPTION
**Pull request by ckyrouac**
The quadlet files are now in the quadlet directory

### CODE REVIEW

**Review by sallyom — APPROVED** [review]
LGTM - thanks!! this was fallout from the rapid development last week :)

**Comment by rhatdan** [comment]
NO this is wrong, we need to convert them and place them in the build directory,  This PR needs to be reverted.

**Comment by sallyom** [comment]
🤦 I took 1 day off and forgot what was going on here - will revert this

**Comment by cgwalters** [comment]
I think what happened here is you're working on the Makefile, which always does the substitution.  But Chris (and me) are working from the gdoc which isn't doing it.

**Comment by rhatdan** [comment]
The Gdoc has a sed line in the Containerfile.

Will update the docs to match the current state of art tomorrow.

**Pull request merged**
