### PR TITLE
update workflow traces

### PR DESCRIPTION
**Pull request by sallyom**
depends on https://github.com/containers/ai-lab-recipes/pull/660
cleanup of workflow traces - testing-workflow traces were broken, not configured correctly

### CODE REVIEW

**Comment by sallyom** [comment]
wait for this to merge before reviewing: https://github.com/containers/ai-lab-recipes/pull/660

**Comment by rhatdan** [comment]
@lmilbaum @Gregory-Pereira PTAL

**Comment by Gregory-Pereira** [comment]
I just resolved conflicts by including your changes, which caused CI issues, going to TAL

**Comment by Gregory-Pereira** [comment]
reverted my merge commit for now

**Comment by Gregory-Pereira** [comment]
After reviewing the conflicts again I don't think the merge commit was the issue. I will allow you to resolve them to verify.

**Comment by rhatdan** [comment]
Needs a rebase.

**Comment by rhatdan** [comment]
Closing since this has not moved in many months, re-open if this is still needed.

**Pull request closed without merging**
