### PR TITLE
Pull instructlab images out of local storage

### PR DESCRIPTION
**Pull request by rhatdan**
Also create a Makefile.common in training so that the different hardware vendors Makefiles can share options.

### CODE REVIEW

**Comment by n1hility** [comment]
LGTM

**Comment by Gregory-Pereira** [comment]
If you can @rhatdan include the workflow changes when possible.

**Comment by rhatdan** [comment]
@Gregory-Pereira what did I change in workflows?

**Comment by Gregory-Pereira** [comment]
The workflows used those make targets to build. I added a commit updating the workflows to use the new `bootc` make target instead of the `image` target it was previously. Were close to testing about 65% makefile coverage in our tests, odds are whenever make targets change it will affect testing infra.

**Comment by rhatdan** [comment]
Ok. sorry.

This patch is broken.  Will be opening another.

**Pull request merged**
