### PR TITLE
Add vendor label and arg to all containerfiles

### PR DESCRIPTION
**Pull request by ralphbean**
So that downstream vendors can indicate themselves on their builds.

I expect we will want to add more of [these](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys) in the future, but this one is a good start.

### CODE REVIEW

**Comment by rhatdan** [comment]
Can you add a mechanism to set the Vendor from the Makefile.

**Comment by rhatdan** [comment]
Not crazy about PROVIDER, but will merge.

What do you think about HARDWARE?

**Review by rhatdan — APPROVED** [review]
LGTM

**Comment by ralphbean** [comment]
Yeah, `HARDWARE` works for me too.

**Pull request merged**
