### PR TITLE
created cloud init workflow and documentation

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Dupe of #429 but moved to upstream branch to enable testing

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM But assigned to Draft.

**Comment by Gregory-Pereira** [comment]
I left it as a draft because in the process of working on this I discovered #431, which renders this pretty much useless as it will not work for both `amd-bootc` and `nvidia-bootc`

**Comment by rhatdan** [comment]
@Gregory-Pereira Anything going on with this one?

**Comment by Gregory-Pereira** [comment]
If there is a need I am happy to pick this up again. The E2E CI methodology no longer uses these images as we directly inject the SSH key. If you still think there is value in this feature beyond this I will pick it up again.

**Pull request closed without merging**
