### PR TITLE
Remove retagging from ilab image

### PR DESCRIPTION
**Pull request by enriquebelarte**
Retag is not needed as we are using static tags now.

### CODE REVIEW

**Review by lmilbaum — APPROVED** [review]
LGTM

**Comment by lmilbaum** [comment]
@pastequo Please review the changes before it is merged

**Comment by rhatdan** [comment]
Are you sure the image in the additional store ends up labeled correctly?

**Comment by pastequo** [comment]
The retag was instaured because without it "podman images" or equivalent was displaying `<none>`

**Comment by enriquebelarte** [comment]
@pastequo  If I'm not mistaken the retag was needed because digest tags made the `podman images ` output show tag field as `<none>` .
We're not using digest tags now but static ones that's why my guess is that the code is not needed anymore.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
