### PR TITLE
move bootc builder (dtk) to common

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Relates to: https://github.com/containers/ai-lab-recipes/pull/585#discussion_r1646422455
Depends on rebase and merge of #585 
/cc @fabiendupont @enriquebelarte

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
CI still needs to be implemented / updated for generic builder but Ill wait for parent PR to rebase in Jasons changes

**Comment by fabiendupont** [comment]
Why not call the image `driver-toolkit`?

**Comment by Gregory-Pereira** [comment]
I was keeping it as it was for consistency but I think since were already moving this we may as well name it in a more friendly way.

**Review by fabiendupont — APPROVED** [review]
/lgtm

**Review by enriquebelarte — APPROVED** [review]
/LGTM

**Pull request merged**
