### PR TITLE
bump python 3.11 to 3.12

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Addresses: https://redhat-internal.slack.com/archives/C06S75ZF9JT/p1717001390671349?thread_ts=1716993243.256019&cid=C06S75ZF9JT
/cc @lmilbaum

### CODE REVIEW

**Comment by lmilbaum** [comment]
CI is broken

**Comment by lmilbaum** [comment]
Not sure all the relevant CI workflows were triggered

**Comment by Gregory-Pereira** [comment]
They were not, not sure we have correct build trigger rules. I will try to fix CI when I get time.

**Comment by sallyom** [comment]
`moduleNotFoundError: No module named 'distutils'` - error w/ CI build

**Comment by Gregory-Pereira** [comment]
`huggingface_hub` module does not have support for python3.12, downgrading the `model_converter`.

**Review by rhatdan — APPROVED** [review]
LGTM

**Pull request merged**
