### PR TITLE
fix convert_models build with build path permissions (temporary)

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
/cc @sallyom @MichaelClifford this was currently breaking the push model image workflow

### CODE REVIEW

**Comment by rhatdan** [comment]
Where did /opt/app/root come from?

**Comment by Gregory-Pereira** [comment]
That is the default (app-root) of the parent container: `FROM registry.access.redhat.com/ubi9/python-311:1-52.1712567218`. In the workflows were solving for a permissions write error: 
```Container build log
STEP 2/7: WORKDIR /converter
STEP 3/7: RUN git clone https://github.com/ggerganov/llama.cpp.git
fatal: could not create work tree dir 'llama.cpp': Permission denied
```

**Comment by Gregory-Pereira** [comment]
This results from the following:
```bash
 $ podman run --rm -it registry.access.redhat.com/ubi9/python-311:1-52.1712567218 /bin/bash
(app-root) cd /
(app-root) ls
afs  bin  boot	dev  etc  help.1  home	lib  lib64  lost+found	media  mnt  opt  proc  root  run  sbin	srv  sys  tmp  usr  var
(app-root) git clone https://github.com/ggerganov/llama.cpp.git
fatal: could not create work tree dir 'llama.cpp': Permission denied
(app-root) mkdir /converter
mkdir: cannot create directory ‘/converter’: Permission denied
```

**Review by sallyom — APPROVED** [review]
LGTM, thank you!

**Comment by Gregory-Pereira** [comment]
Since you approve sally I think we can merge this, as we are hotfixing the integration tests anyway, more PRs can follow to cleanup.

**Comment by sallyom** [comment]
Try with the original Containerfile, but remove the slash `/` from `/converter`

**Pull request merged**
