### PR TITLE
Add building of instructlab container images

### PR DESCRIPTION
**Pull request by rhatdan**
Currently not sure we need this, but it is worth playing with.

### CODE REVIEW

**Comment by stefwalter** [comment]
This is working (building) for me.

FWIW, Seems to be needed. There needs to be a way to build all of this together with the images in the amd/nvidia/intel bootable container images.

**Comment by rhatdan** [comment]
Ok removed [WIP]

Just need to figure out how to push them to ai-lab.

**Comment by stefwalter** [comment]
Built nvidia image as: https://quay.io/repository/swalter/instructlab-nvidia

```
$ podman pull quay.io/swalter/instructlab-nvidia:latest
```

**Comment by stefwalter** [comment]
We could use these e2e tests to ensure that these work: https://github.com/instructlab/instructlab/pull/1016

**Pull request merged**
