### PR TITLE
Recipe for a simple Quarkus-based chatbot

### PR DESCRIPTION
**Pull request by jmartisk**
Java example based on Quarkus and its LangChain4j extension, as an alternative to the Python/LangChain chatbots.

If accepted, I would also add this to the recipe catalog. Right now, to try this out, one can put this into `$HOME/.local/share/containers/podman-desktop/extensions-storage/redhat.ai-lab/user-catalog.json`: 

```
{
  "version": "1.0",
  "recipes": [
    {
      "id": "chatbot-java",
      "description": "This is a Java-based chat demo application.",
      "name": "Java-based ChatBot",
      "repository": "https://github.com/jmartisk/ai-lab-recipes",
      "ref": "quarkus-recipe",
      "icon": "natural-language-processing",
      "categories": ["natural-language-processing"],
      "basedir": "recipes/natural_language_processing/chatbot-java",
      "readme": "README TBD",
      "recommended": [
        "hf.instructlab.granite-7b-lab-GGUF",
        "hf.instructlab.merlinite-7b-lab-GGUF",
        "hf.lmstudio-community.granite-3.0-8b-instruct-GGUF"
      ],
      "backend": "llama-cpp"
    }
  ]
}  
```

### CODE REVIEW

**Review by rhatdan — APPROVED** [review]
LGTM

**Comment by slemeur** [comment]
Thanks for the contribution @jmartisk !

**Comment by slemeur** [comment]
Working properly on my side! 

Pretty cool :)

Screenshot 2024-11-07 at 14 28 52

**Comment by axel7083** [comment]
Hi @jmartisk amazing job!

I just have one remark, when the inference service is not available (let's say I stop the inference server after I start the recipe), I am stuck in this loading spinner;

image

question (non-blocking): could we add an error handling to show something when the server cannot contact the inference server ?

**Comment by jmartisk** [comment]
@axel7083 OK, I've added a simple message that informs the user about it, rather than keep them waiting forever.

**Comment by jmartisk** [comment]
Should we also have an image with the application deployed in quay.io, like the other recipes have? Would somebody from the podman team take care of building and updating it, or how would that work?

**Comment by jeffmaury** [comment]
> Should we also have an image with the application deployed in quay.io, like the other recipes have? Would somebody from the podman team take care of building and updating it, or how would that work?

The team managing this repository is currently transitioning so I would first see this as a future enhancement and merge this before

**Comment by rhatdan** [comment]
Yes the Podman team does not manage this Repo. I do, but I am no longer on that team.  Hopefully we will have full time people on this soon and then we can get management of container images straightened out.

**Comment by rhatdan** [comment]
I am also not sure we have any images outside of training?

**Pull request merged**
