### PR TITLE
Adding rhc for telemetry

### PR DESCRIPTION
**Pull request by tsorya**
Adding rhc in order to gather telemetry with insights client.
We need to be able to run rhc connect, should run only on rhel

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
Can you fill me in on the reasoning around the hold? Just want to understand if there is a specific reason were waiting on this.

**Comment by tsorya** [comment]
Had a problem with running the image, held for better testing (though had same problem with main branch)

**Review by rhatdan — APPROVED** [review]
LGTM

**Pull request merged**
