### PR TITLE
RHELAI-1474 - Install Google Ops Agent

### PR DESCRIPTION
**Pull request by javipolo**
/cc @cdvultur

### CODE REVIEW

**Comment by lmilbaum** [comment]
@fabiendupont Is working on splitting the training code to a different git repo. Should this change contributed in that repo instead of this one?

**Comment by javipolo** [comment]
I think this repo is still the source of truth for the Konflux pipelines, so I guess the changes should go to both repos

Let's wait for Fabien to clarify

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
