### PR TITLE
Add BASEIMAGE as argument to Containerfile

### PR DESCRIPTION
**Pull request by enriquebelarte**
Added BASEIMAGE as ARG so it can be used from build.

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
This is what the `--from` directive does. Ex:
```bash
echo "FROM scratch" > Containerfile
podman build --from="registry.redhat.io/ubi9/ubi:latest" . -f Containerfile -t testing
STEP 1/1: FROM registry.redhat.io/ubi9/ubi:latest
COMMIT testing
--> 261134d03e83
Successfully tagged localhost/testing:latest
Successfully tagged registry.redhat.io/ubi9/ubi:latest
Successfully tagged registry.access.redhat.com/ubi9/ubi:latest
261134d03e83034da5dce51c49a45807633c79aa4355c9d57ff7d452a649aa7c
```
Feel free to read more about this in the [podman docs](https://docs.podman.io/en/stable/markdown/podman-build.1.html#from).

If, knowing all this, there is some reason to keep this as a separate build arg instead of from please let me know.

**Comment by enriquebelarte** [comment]
Konflux CI takes Containerfile and builds it with its own pipeline where unless I'm mistaken we can only use build-args. Hence the change. It is done this way on [others](https://github.com/containers/ai-lab-recipes/blob/main/training/intel-bootc/Containerfile#L1).

**Review by Gregory-Pereira — APPROVED** [review]
/lgtm

**Comment by rhatdan** [comment]
Are  you planning on opening similar PRs for invidia-bootc and intel-bootc?

**Pull request merged**
