### PR TITLE
change use of auth.json to use local file rather then XDG_RUNTIME_DIR

### LINKED ISSUE #151: docs reference XDG_RUNTIME_DIR
The [docs](https://github.com/containers/ai-lab-recipes/tree/main/recipes/natural_language_processing/chatbot/bootc) mention XDG_RUNTIME_DIR for mounting the auth.json file:
```
podman build --build-arg "sshpubkey=$(cat ~/.ssh/id_rsa.pub)" \
           --security-opt label=disable \
	   -v ${XDG_RUNTIME_DIR}/containers/auth.json:/run/containers/0/auth.json \
	   --cap-add SYS_ADMIN \
	   -t quay.io/yourrepo/youros:tag .
```

The docs further mention building on the Mac.  But, on the Mac the file resides in $HOME/.config/containers/auth.json.

I think the docs need some tweaking to be portable across Linux/Mac/Win.

### PR DESCRIPTION
**Pull request by rhatdan**
This allows docs to work on Mac and Windows platform.

Fixes: https://github.com/containers/ai-lab-recipes/issues/151

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by rhatdan** [comment]
@sallyom @MichaelClifford PTAL

**Review by sallyom — APPROVED** [review]
LGTM!

**Review by vrothberg — COMMENTED** [review]
LGTM, thanks!

**Pull request merged**
