### PR TITLE
udpate otel-collector workflow config

### PR DESCRIPTION
**Pull request by sallyom**
updates workflow otel-collector config with mTLS and ROSA endpoint

### CODE REVIEW

**Comment by sallyom** [comment]
Traces are reaching OpenShift (ROSA) otel-collector, yay! - not sure how useful the trace data is, but now that we have the connection in place, we can update the telemetry collected. 
Screenshot 2024-06-24 at 11 14 36 PM

**Comment by sallyom** [comment]
I think this is a good start. Workflow jobs (only chatbot for now) create a single trace to track how long the job took to complete 
Screenshot 2024-06-25 at 12 12 40 PM

**Comment by rhatdan** [comment]
@Gregory-Pereira @lmilbaum PTAL

**Review by Gregory-Pereira — APPROVED** [review]
/lgtm

**Pull request merged**
