### PR TITLE
Add libdnf workaround for intel-bootc

### PR DESCRIPTION
**Pull request by enriquebelarte**
Same as in https://github.com/containers/ai-lab-recipes/pull/630 a workaround is applied in order to install needed packages with `dnf`

### CODE REVIEW

**Comment by rhatdan** [comment]
Is the issue that SELinux labels are attempting to be added?

**Comment by enriquebelarte** [comment]
Yes, that's the issue.

**Review by Gregory-Pereira — APPROVED** [review]
/lgtm

**Comment by rhatdan** [comment]
This needs a rebase, but I would really like to remove this hack and figure out how SELinux being enabled is leaking into the container when using Konflux.

**Comment by cgwalters** [comment]
@rhatdan It's all in https://issues.redhat.com/browse/RHEL-39796 - bug in libdnf

**Comment by rhatdan** [comment]
Thanks @cgwalters 
I was thinking that selinuxenabled was returning true, but it looks by the links that libdnf was not even checking if SELinux was enabled.

LGTM, after rebase.

**Comment by enriquebelarte** [comment]
Closing in favor of https://github.com/containers/ai-lab-recipes/pull/780

**Pull request closed without merging**
