### PR TITLE
Add experimental llamacpp/vulkan server

### PR DESCRIPTION
**Pull request by slp**
Refactor playground to support multiple model servers, and implement a vulkan variant.

### CODE REVIEW

**Comment by MichaelClifford** [comment]
Thanks for the PR @slp. I plan on depreciating this recipe soon in place of an updated one that relies on a shared model server. 

Could you add this Containerfile to a new directory instead `locallm/model_servers/llamacpp/vulkan/` ?

**Comment by slp** [comment]
@MichaelClifford I've updated the PR to refactor `playground` as `model_servers`. PTAL.

**Comment by MichaelClifford** [comment]
Could you please move these files to a new directory `model_servers/` and not update the `playground/` directory right now. [AI Studio](https://github.com/projectatomic/ai-studio) relies on the playground and I'd would prefer to no make too many changes there just yet.

**Comment by MichaelClifford** [comment]
It might look slightly duplicative at the moment, but as we add additional model servers that may or may not be used by the playground, I'd like to have a clear place for them in the repo.

**Comment by slp** [comment]
Sure, no problem, I'll update the PR.

**Comment by slp** [comment]
Done. Please let me know if it needs more adjustments.

**Pull request merged**
